FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY . /app
WORKDIR /app/SimpleMemory.Tests
RUN dotnet restore SimpleMemory.Tests.csproj
RUN dotnet test