version: "3"
services:
  app:
    build: 
      context: .
      dockerfile: Packaging/dockerfile.dev
    container_name: "simple_memory_dev"
    ports:
      - 5000:5000
    volumes:
      - .:/app
    command: ["dotnet", "watch", "run"]